#! usr/bin/python
# -*- coding:utf-8 -*-
from flask import Flask, url_for, session, redirect, request, Response, make_response
from flask import render_template, flash, jsonify, json

app = Flask(__name__)

"""
def do_the_login():
    return 'test1'


def show_the_login_form():
    return 'test2'


@app.route('/hello/')
@app.route('/hello/<name>')
def hello(name=None):
    return render_template('hello.html', name=name)


@app.route('/index')
def index(): pass


@app.route('/')
def show_entries():
    cur = g.db.execute('select title, text from entries order by id desc')
    entries = [dict(title=row[0], text=row[1]) for row in cur.fetchall()]
    return render_template('show_entries.html', entries=entries)


@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != app.config['USERNAME']:
            error = 'Invalid username'
        elif request.form['password'] != app.config['PASSWORD']:
            error = 'Invalid password'
        else:
            session['logged_in'] = True
            flash('You were logged in')
            return redirect(url_for('show_entries'))
    return render_template('login.html', error=error)


@app.route('/user/<username>')
def profile(username):
    return 'hello %s' % username


with app.test_request_context():
    print url_for('index')
    print url_for('login')
    print url_for('login', next='/')
    print url_for('profile', username='John Doe')

"""


def is_num_by_except(num):
    try:
        int(num)
        return True
    except ValueError:
        return False


@app.route('/test1/', methods=['GET', 'POST'])
def test1():
    if request.method == 'GET':
        return render_template('test1.html')
    elif request.method == 'POST':
        add1 = is_num_by_except(request.form.get('add1'))
        add2 = is_num_by_except(request.form.get('add2'))
        if add1 is False or add2 is False:
            result = 'please input number!'
        else:
            result = (int(request.form.get('add1'))+int(request.form.get('add2')))
        print 'lxf test %s' % result
        return render_template('test1.html', result=result)


@app.route('/test2')
def test2():
        add1 = request.args.get('a', 0, type=int)
        add2 = request.args.get('b', 0, type=int)
        return jsonify(result=add1+add2)


@app.route('/test3', methods=['GET'])
def test3():
        add1 = request.args.get('a', 0, type=int)
        add2 = request.args.get('b', 0, type=int)
        # result = jsonify(result=add1+add2)
        # response = make_response('<h1>test3</h1>')
        # response.set_cookie('answer', '42')
        # response.headers['X-Parachutes'] = 'parachutes are cool'
        # response.status_code = 200
        # response.data = ('result', add1+add2)
        # # response.set_data['result'] = jsonify(result=add1+add2)
        # print 'test3 response.headers %s' % response.headers
        # print 'test3 response.data %s' % response.data
        result = add1+add2
        response_result = {'result': result}
        print 'response_result %s,%s,%s' % (add1, add2, response_result)
        res = Response(response=response_result, status=200, mimetype='application/json')
        print 'test3 res %s' % res.response
        return res


@app.route('/')
def index():
    return render_template('test2.html')


@app.route('/example/', methods=['GET', 'POST'])
def example():
    return render_template('example.html')

# if __name__ == '__main__':
#     app.run(debug=True)
